#!/bin/bash

CONCOURSE_VERSION=

# function do_purge(version)
function do_purge() {
  local VERSION="${1}"

  if [ -d /var/cache/concourse -a "$(ls -1 /var/cache/concourse | wc -l)" = "0" -a ! -x /usr/bin/concourse-web ]; then
    rm -r /var/cache/concourse
  fi

  mount | grep /var/lib/concourse/workspace/volumes > /dev/null

  if [ $? -eq 0 ]; then
    umount /var/lib/concourse/workspace/volumes

    sync
  fi

  for device in $(losetup -j /var/lib/concourse/workspace/volumes.img | cut -f1 -d:); do
    losetup -d "${device}"
  done

  if [ -d /var/lib/concourse/workspace ]; then
    rm -r /var/lib/concourse/workspace
  fi

  if [ -d /var/lib/concourse -a "$(ls -1 /var/lib/concourse | wc -l)" = "0" ]; then
    rm -r /var/lib/concourse
  fi
}

# function do_remove(version)
function do_remove() {
  local VERSION="${1}"
}

case "${1}" in
  purge)
    do_purge "${CONCOURSE_VERSION}"
    ;;
  remove)
    do_remove "${CONCOURSE_VERSION}"
    ;;
  upgrade)
    do_remove "${2}"
    ;;
esac
