#!/bin/bash

CONCOURSE_VERSION=

# function do_remove(version, delete_keys)
function do_remove() {
  local VERSION="${1}"
  local DELETE_KEYS="${2}"

  systemctl status concourse-worker > /dev/null 2> /dev/null

  if [ $? -eq 0 ]; then
    if [ -f /etc/concourse/worker ]; then
      source /etc/concourse/worker
    fi

    local WORKER_NAME="${CONCOURSE_NAME:-$(hostname)}"
    local TSA_HOST="${CONCOURSE_TSA_HOST:-127.0.0.1}"
    local TSA_PUBLIC_KEY="${CONCOURSE_TSA_PUBLIC_KEY:-/usr/lib/concourse/host_key.pub}"
    local TSA_WORKER_PRIVATE_KEY="${CONCOURSE_TSA_WORKER_PRIVATE_KEY:-/usr/lib/concourse/worker_key}"

    concourse retire-worker --name "${WORKER_NAME}" --tsa-host="${TSA_HOST}" --tsa-public-key="${TSA_PUBLIC_KEY}" --tsa-worker-private-key="${TSA_WORKER_PRIVATE_KEY}" > /dev/null

    if [ $? -ne 0 ]; then
      systemctl stop concourse-worker
    fi

    systemctl status concourse-worker > /dev/null

    while [ $? -ne 3 ]; do
        sleep 1

        systemctl status concourse-worker > /dev/null
    done
  fi

  systemctl stop concourse-worker
  systemctl disable concourse-worker 2> /dev/null
  systemctl daemon-reload

  if "${DELETE_KEYS}"; then
    if [ -f /usr/lib/concourse/worker_key ]; then
      rm /usr/lib/concourse/worker_key
      rm /usr/lib/concourse/worker_key.pub
    fi
  fi

  if [ -d /usr/lib/concourse -a "$(ls -11 /usr/lib/concourse | wc -l)" = "0" ]; then
    rm -r /usr/lib/concourse
  fi

  if [ -d "/var/lib/concourse/workspace/${CONCOURSE_VERSION}" ]; then
    rm -r "/var/lib/concourse/workspace/${CONCOURSE_VERSION}"
  fi
}

case "${1}" in
  failed-upgrade)
    VERSION="${2}"
    ;;
  remove)
    do_remove "${CONCOURSE_VERSION}" true
    ;;
  upgrade)
    do_remove "${2}" false
    ;;
esac
