#!/bin/bash

CONCOURSE_VERSION=

# function do_remove(version, delete_keys)
function do_remove() {
  local VERSION="${1}"
  local DELETE_KEYS="${2}"

  systemctl stop concourse-worker
  systemctl disable concourse-worker 2> /dev/null
  systemctl daemon-reload

  if "${DELETE_KEYS}"; then
    if [ -f /usr/lib/concourse/worker_key ]; then
      rm /usr/lib/concourse/worker_key
      rm /usr/lib/concourse/worker_key.pub
    fi
  fi

  if [ -d /usr/lib/concourse -a "$(ls -11 /usr/lib/concourse | wc -l)" = "0" ]; then
    rm -r /usr/lib/concourse
  fi

  if [ -d "/var/lib/concourse/workspace/${CONCOURSE_VERSION}" ]; then
    rm -r "/var/lib/concourse/workspace/${CONCOURSE_VERSION}"
  fi
}

case "${1}" in
  failed-upgrade)
    VERSION="${2}"
    ;;
  remove)
    do_remove "${CONCOURSE_VERSION}" true
    ;;
  upgrade)
    do_remove "${2}" false
    ;;
esac
