#!/bin/bash

HOST_ADDRESS=$(ifconfig eth0 | grep -E 'inet\b' | awk '{ print $2 }')
HOST_NAME=$(hostname)

if [ -f /etc/concourse/web ]; then
  source /etc/concourse/web
fi

for VAR in "${!CONCOURSE@}"; do
  export "${VAR}"
done

AUTHORIZED_WORKERS=""

for KEY in /usr/lib/concourse/worker*.pub; do
  AUTHORIZED_WORKERS="${AUTHORIZED_WORKERS}$(cat ${KEY})\n"
done

echo -en "${AUTHORIZED_WORKERS}" > /var/lib/concourse/authorized_worker_keys

/usr/bin/concourse web
